#!/bin/bash

set -e
set +x

ROOT=$(dirname "${BASH_SOURCE[0]}" )

cores=4
memory=1g
records=1000

datasets=(
	"sorted-asc"
	"sorted-desc"
	"single"
	"uniform"
	"skewed"
)

for dataset in "${datasets[@]}"; do
    input=$ROOT/data-$dataset.tsv
	if [ ! -f $input ]; then
		python3 $ROOT/datagen.py $dataset $records $input
	fi

    tst=string-search
    echo "=== RUN   $dataset-$tst"
    output=$ROOT/output-$tst-$dataset
    log=$ROOT/log-$tst-$dataset.log
    profile=$ROOT/profile-$tst-$dataset.profile
    rm -f -r $output
    rm -f $log
    rm -f $profile
    $ROOT/../xrt --mappers $cores \
                 --reducers $cores \
                 --memory $memory \
                 --input $input \
                 --mapper "python3 $ROOT/$tst/map.py" \
                 --output $output &> $log \
                 --profile $profile
    if python3 $ROOT/$tst/check.py $input $output; then
        echo "--- PASS: $dataset-$tst"
    else
        echo "--- FAIL: $dataset-$tst"
        exit 1
    fi

    tst=parallel-sort
    echo "=== RUN   $dataset-$tst"
    output=$ROOT/output-$tst-$dataset
    log=$ROOT/log-$tst-$dataset.log
    profile=$ROOT/profile-$tst-$dataset.profile
    rm -f -r $output
    rm -f $log
    rm -f $profile
    $ROOT/../xrt --mappers $cores \
                 --reducers $cores \
                 --memory $memory \
                 --input $input \
                 --mapper "python3 $ROOT/$tst/map.py" \
                 --reducer "python3 $ROOT/$tst/reduce.py" \
                 --output $output &> $log \
                 --profile $profile
    if python3 $ROOT/$tst/check.py $input $output; then
        echo "--- PASS: $dataset-$tst"
    else
        echo "--- FAIL: $dataset-$tst"
        exit 1
    fi

    tst=word-count
    echo "=== RUN   $dataset-$tst"
    output=$ROOT/output-$tst-$dataset
    log=$ROOT/log-$tst-$dataset.log
    profile=$ROOT/profile-$tst-$dataset.profile
    rm -f -r $output
    rm -f $log
    rm -f $profile
    $ROOT/../xrt --mappers $cores \
                 --reducers $cores \
                 --memory $memory \
                 --input $input \
                 --mapper "python3 $ROOT/$tst/map.py" \
                 --reducer "python3 $ROOT/$tst/reduce.py" \
                 --output $output &> $log \
                 --profile $profile
    if python3 $ROOT/$tst/check.py $input $output; then
        echo "--- PASS: $dataset-$tst"
    else
        echo "--- FAIL: $dataset-$tst"
        exit 1
    fi
done

echo "PASS"
echo "ok  	integration"
