#!/bin/bash

set -e
set +x

ROOT=$(dirname "${BASH_SOURCE[0]}" )

cores=4
records=1000

memory=(
	"16m"
	"16k"
)

datasets=(
	"sorted-asc"
	"sorted-desc"
	"single"
	"uniform"
	"skewed"
)

for dataset in "${datasets[@]}"; do
	input=$ROOT/data-$dataset.tsv
	if [ ! -f $input ]; then
		python3 $ROOT/datagen.py $dataset $records $input
	fi

	for mem in "${memory[@]}"; do

		tst=string-search
		echo "=== RUN   $tst-$dataset-$mem"
		output=$ROOT/output-$tst-$dataset-$mem
		log=$ROOT/log-$tst-$dataset-$mem.log
		profile=$ROOT/profile-$tst-$dataset-$mem.profile
		rm -f -r $output
		rm -f $log
		rm -f $profile
		$ROOT/../xrt --mappers $cores \
					 --reducers $cores \
					 --memory $mem \
					 --input $input \
					 --mapper "python3 $ROOT/$tst/map.py" \
					 --output $output &> $log \
					 --profile $profile
		if python3 $ROOT/$tst/check.py $input $output; then
			echo "--- PASS: $tst-$dataset-$mem"
		else
			echo "--- FAIL: $tst-$dataset-$mem"
			exit 1
		fi

		tst=parallel-sort
		echo "=== RUN   $tst-$dataset-$mem"
		output=$ROOT/output-$tst-$dataset-$mem
		log=$ROOT/log-$tst-$dataset-$mem.log
		profile=$ROOT/profile-$tst-$dataset-$mem.profile
		rm -f -r $output
		rm -f $log
		rm -f $profile
		$ROOT/../xrt --mappers $cores \
					 --reducers $cores \
					 --memory $mem \
					 --input $input \
					 --mapper "python3 $ROOT/$tst/map.py" \
					 --reducer "python3 $ROOT/$tst/reduce.py" \
					 --output $output &> $log \
					 --profile $profile
		if python3 $ROOT/$tst/check.py $input $output; then
			echo "--- PASS: $tst-$dataset-$mem"
		else
			echo "--- FAIL: $tst-$dataset-$mem"
			exit 1
		fi

		tst=word-count
		echo "=== RUN   $tst-$dataset-$mem"
		output=$ROOT/output-$tst-$dataset-$mem
		log=$ROOT/log-$tst-$dataset-$mem.log
		profile=$ROOT/profile-$tst-$dataset-$mem.profile
		rm -f -r $output
		rm -f $log
		rm -f $profile
		$ROOT/../xrt --mappers $cores \
					 --reducers $cores \
					 --memory $mem \
					 --input $input \
					 --mapper "python3 $ROOT/$tst/map.py" \
					 --reducer "python3 $ROOT/$tst/reduce.py" \
					 --output $output &> $log \
					 --profile $profile
		if python3 $ROOT/$tst/check.py $input $output; then
			echo "--- PASS: $tst-$dataset-$mem"
		else
			echo "--- FAIL: $tst-$dataset-$mem"
			exit 1
		fi
	done
done

echo "PASS"
echo "ok  	integration"
